spring:
  datasource:
    basic:
      url: jdbc:mysql://localhost/db_cloud_basic
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
      redis:
        oauth2:
          host: localhost
          port: 6379
          database: 11
          password: 23456
          max-idle: 100
          max-total: 200
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update