spring:
  datasource:
    basic:
      url: jdbc:mysql://localhost/db_cloud_basic?serverTimezone=GMT%2B8
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    oauth2:
      host: localhost
      port: 6379
      database: 11
      password: 123456
      max-idle: 100
      max-total: 200
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update