spring:
  datasource:
    basic:
      url: jdbc:mysql://localhost/db_cloud_basic
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update