spring:
  datasource:
    basic:
      url: jdbc:mysql://192.168.33.206:3326/db_cloud_basic
      username: root
      password: lvyuebbk@123456
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    oauth2:
      host: 192.168.33.206
      port: 6379
      database: 11
      password: lvyue@123456
      max-idle: 100
      max-total: 200
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update