spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangzhangmao/spring-boot-cloud
          search-paths: config-repo
          timeout: 300
          username: wangzhangmao
          password: password
server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/