spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LIYANCHUN339/spring-boot-cloud
          search-paths: config-repo
          timeout: 300
          username: LIYANCHUN339
          password: li512918
server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/